[[redirects]]
    from = "/home"
    to = "/home"
    status = 200

[[redirects]]
    from = "/"
    to = "/home"
    status = 200

[[redirects]]
    from = "/about"
    to = "/about"
    status = 200

[[redirects]]
    from = "/projects"
    to = "/projects"
    status = 200

[[redirects]]
    from = "/contact"
    to = "/contact"
    status = 200

[[redirects]]
    from = "/*"
    to = "/404"
    status = 404
